name: 🚀 Deploy website on push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Cloudhosting
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.asaurusedu.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
      
