name: 🚀 Code Linting Check

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Cloudhosting
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Setup Prettier
        run: yarn install --cache-folder .yarn --frozen-lockfile


      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP CS Fixer
        uses: php-actions/composer@v6
      
      - name: Run Code Linting
        run: composer run lint

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.asaurusedu.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/
          dry-run: false
      
